data:extend{
	{
		type = "string-setting",
		name = "functional-gleba-map-colors-agricultural-stage",
		setting_type = "startup",
		order = "01",
		default_value = "unspecified",
		allowed_values = {
			"unspecified",
			"natural",
			"artificial",
			"overgrowth",
		},
	},
	{
		type = "string-setting",
		name = "functional-gleba-map-colors-agricultural-stage-contrast",
		setting_type = "startup",
		order = "02",
		default_value = "moderate",
		allowed_values = {
			"very-high",
			"high",
			"moderate",
			"low",
			"very-low",
		},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-high-fertility-yumako-color",
		setting_type = "startup",
		order = "03",
		default_value = {120, 180, 0},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-low-fertility-yumako-color",
		setting_type = "startup",
		order = "04",
		default_value = {60, 90, 0},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-artificial-yumako-color",
		setting_type = "startup",
		order = "05",
		default_value = {150, 180, 75},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-high-fertility-jellynut-color",
		setting_type = "startup",
		order = "06",
		default_value = {210, 60, 210},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-low-fertility-jellynut-color",
		setting_type = "startup",
		order = "07",
		default_value = {90, 30, 90},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-artificial-jellynut-color",
		setting_type = "startup",
		order = "08",
		default_value = {225, 105, 210},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-highland-color",
		setting_type = "startup",
		order = "09",
		default_value = {120, 90, 60},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-midland-color",
		setting_type = "startup",
		order = "10",
		default_value = {105, 75, 45},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-lowland-color",
		setting_type = "startup",
		order = "11",
		default_value = {75, 60, 60},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-shallow-water-color",
		setting_type = "startup",
		order = "12",
		default_value = {30, 45, 90},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-deep-water-color",
		setting_type = "startup",
		order = "13",
		default_value = {15, 30, 60},
	},
	{
		type = "color-setting",
		name = "functional-gleba-map-colors-other-color",
		setting_type = "startup",
		order = "14",
		default_value = {75, 75, 75},
	},
}
